- name: Downloads, unpacks, and links in a stack
  hosts: localhost
  vars_files:
    - ./variables.yml
    - ../global_variables.yml
    - ../config/user_settings.yml
  vars:
    - stroom_url: "https://github.com/gchq/stroom-resources/releases/download/stroom-stacks-{{ stack_version }}/{{ stack_name }}-{{ stack_version}}.tar.gz"
  roles:
    - roles/stack/download
