---
- name: Setup all hosts, installing dependencies such as docker
  become: yes
  hosts: all
  vars_files:
    - ./variables.yml
    - ../global_variables.yml
    - ../config/user_settings.yml
  roles:
    - roles/setup
