- name: Copy stack to remote
  copy:
    src: "{{releases_path}}/{{stack_name}}-{{stack_version}}"
    dest: "{{home}}/{{stack_name}}"

- name: Create a symlink to a predictable location
  file:
    state: link
    src: "{{home}}/{{stack_name}}/{{stack_name}}-{{stack_version}}"
    dest: "{{home}}/{{stack_name}}/latest"
