version: "3"

services:

  stroom-proxy:
    image: gchq/stroom-proxy:latest
    ports:
      - 8085:8085

  stroom-stats:
    image: gchq/stroom-stats:latest
    # Stroom-stats in a container is configured by setting environment variables.
    # What's shown below is the minimum configuration for production. Everything else has sensible defaults.
    #
    # Probably the only environment variables that will need setting for development are STATS_DB_URL and STATS_ZK_QUORUM.
    #
    # The environment variables are transposed into the Dropwizard config file (stroom-stats-service/config.yml).
    # See that file for other settable environment variables.
    #
    # The ../../bin/runDeploy.sh script replaces the <TOKENS> with actual values.
    environment:
      - STATS_DB_USER=stroomuser
      - STATS_DB_PASSWORD=stroompassword1
      - STATS_DB_URL=jdbc:mysql://<STATS_DB_IP>:3307/stroom?useUnicode=yes&characterEncoding=UTF-8
      - STATS_JWT_SECRET=CHANGE_ME
      - STATS_ZK_QUORUM=<STATS_ZK_IP>:2181
      - STATS_KAFKA_BOOTSTRAP=<KAFKA_IP>:9092
      - STATS_HBASE_ZK_QUORUM=<HBASE_ZK_IP>:2181
      - ADMIN_CONTEXT_PATH=/stats/admin
    ports:
      - 8086:8086
      - 8087:8087
    extra_hosts:
      - hbase:<HBASE_ZK_IP>
      - kafka:<KAFKA_IP>

  stroom-auth-service:
    image: gchq/stroom-auth-service:latest
    environment:
      - DB_USER=stroomuser
      - DB_PASSWORD=stroompassword1
      - DB_URL=jdbc:mysql://<USER_DB_IP>:3307/stroom?useUnicode=yes&characterEncoding=UTF-8
      - JWS_SECRET=CHANGE_ME
      - ADMIN_CONTEXT_PATH=/auth/admin
    ports:
      - 8096:8096
      - 8097:8097

  stroom-auth-ui:
    image: gchq/stroom-auth-ui:latest
    environment:
      - REACT_APP_STROOM_AUTH_SERVICE_URL=http://stroom-auth-service:8096
      - REACT_APP_STROOM_UI_URL=http://localhost:8080
    ports:
      - 5000:5000
