version: '2.1'

services:

  elasticsearch:
    image: "${ELASTIC_DOCKER_REPO:-docker.elastic.co/elasticsearch/elasticsearch}:5.6.3"
    container_name: elasticsearch
    volumes:
      - ./config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
