version: '2.4'

services:
  fake-smtp:
    container_name: fake-smtp
    image: "${FAKE_SMTP_DOCKER_REPO:-munkyboy/fakesmtp}"
    ports:
      - "2525:25"
    volumes:
      - type: volume
        source: fake-smtp_mail
        target: /var/mail
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"

# This volume is specified here instead of everything.yml because this file is used 
# in a standalone fashion, as well as being part of the bounceIt.sh stack.
volumes:
  fake-smtp_mail:
