version: '2.1'

services:
  fake-smtp:
    container_name: fake-smtp
    image: "${FAKE_SMTP_DOCKER_REPO:-munkyboy/fakesmtp}"
    ports:
      - "2525:25"
    volumes:
      - ~/.stroom/fakemail:/var/mail
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"