#Runs an HBase instance with its required zookeeper
version: '2'

services: 

  hbase:
    container_name: hbase
    build: ../../../dev-resources/images/hbase
    image: stroom-stats/hbase
    #hostname: stroom.hbase
    hostname: hbase
    entrypoint: ["./wait-for-it_busybox.sh", "zookeeper:2181"]
    command: ["--", "/entrypoint.sh"]
    environment:
      - HBASE_MANAGES_ZK=false
    ports:
      #- 8080:8080
      #- 8085:8085
      #- 9090:9090
      #- 9095:9095
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
      - 60000:60000
      - 60010:60010
      - 60020:60020
      - 60030:60030
