#Runs an HBase instance with its required zookeeper
version: '2.1'

services: 

  hbase:
    container_name: hbase
    image: "${STROOM_STATS_HBASE_DOCKER_REPO:-gchq/stroom-stats-hbase}:${STROOM_STATS_TAG:-master-SNAPSHOT}_hbase-v1.2.0"
    #hostname: stroom.hbase
    hostname: hbase
    entrypoint: ["./wait-for-it_busybox.sh", "${ZOOKEEPER_QUORUM:-zookeeper:2181}"]
    command: ["--", "/entrypoint.sh"]
    environment:
      - HBASE_MANAGES_ZK=false
    ports:
      #- 8080:8080
      #- 8085:8085
      #- 9090:9090
      #- 9095:9095
      - 16000:16000
      - 16010:16010
      - 16201:16201
      - 16301:16301
      - 60000:60000
      - 60010:60010
      - 60020:60020
      - 60030:60030
