version: '2.1'
services:
  nginx:
    container_name: nginx
    image: "${STROOM_NGINX_DOCKER_REPO:-gchq/stroom-nginx}:${STROOM_NGINX_TAG:-v1.0-LATEST}"
    environment:
      - NGINX_ADVERTISED_HOST=${NGINX_HOST:-stroom-nginx}
      - NGINX_SSL_VERIFY_CLIENT=${NGINX_SSL_VERIFY_CLIENT:-on}
      - NGINX_SSL_CERTIFICATE=${NGINX_SSL_CERTIFICATE:-server.pem.crt}
      - NGINX_SSL_CERTIFICATE_KEY=${NGINX_SSL_CERTIFICATE_KEY:-server.unencrypted.key}
      - NGINX_SSL_CLIENT_CERTIFICATE=${NGINX_SSL_CLIENT_CERTIFICATE:-ca.pem.crt}
      - AUTH_UI_URL=${STROOM_AUTH_UI_URL:-http://localhost:5000}
      - ANNOTATIONS_UI_URL=${STROOM_ANNOTATIONS_UI_URL:-http://localhost:5001}
      - QUERY_ELASTIC_UI_URL=${STROOM_QUERY_ELASTIC_UI_URL:-http://localhost:5002}
      - STROOM_HOST=${STROOM_HOST:-localhost}
      - STROOM_PORT=${STROOM_APP_PORT:-8080}
      - STROOM_AUTH_SERVICE_PORT=${STROOM_AUTH_SERVICE_PORT:-8080}
    volumes:
      # Shared certs volume: TODO: move it to the top level
      - ../../../dev-resources/certs/server:/etc/nginx/certs
      # nginx.conf.template - used to create the actual config when the container starts
      - ../../../stroom-nginx/template:/etc/nginx/template
    ports:
      - "80:80"
      - "443:443"
