version: '2.4'
services:
  nginx:
    container_name: nginx
    image: "${STROOM_NGINX_DOCKER_REPO:-gchq/stroom-nginx}:${STROOM_NGINX_TAG:-v1.0-LATEST}"
    environment:
      - NGINX_ADVERTISED_HOST=${NGINX_ADVERTISED_HOST:-$HOST_IP}
      - NGINX_SSL_VERIFY_CLIENT=${NGINX_SSL_VERIFY_CLIENT:-off}
      - NGINX_SSL_CERTIFICATE=${NGINX_SSL_CERTIFICATE:-server.pem.crt}
      - NGINX_SSL_CERTIFICATE_KEY=${NGINX_SSL_CERTIFICATE_KEY:-server.unencrypted.key}
      - NGINX_SSL_CLIENT_CERTIFICATE=${NGINX_SSL_CLIENT_CERTIFICATE:-ca.pem.crt}
      - NGINX_CLIENT_BODY_BUFFER_SIZE=${NGINX_CLIENT_BODY_BUFFER_SIZE:-1M}
      - AUTH_UI_URL=${STROOM_AUTH_UI_URL:-$HOST_IP:5000}
      - AUTH_SERVICE_PORT=${STROOM_AUTH_SERVICE_PORT:-8099}
      - ANNOTATIONS_UI_URL=${STROOM_ANNOTATIONS_UI_URL:-http://$HOST_IP:5001}
      - QUERY_ELASTIC_UI_URL=${STROOM_QUERY_ELASTIC_UI_URL:-http://$HOST_IP:5002}
      - STROOM_HOST=${STROOM_HOST:-$HOST_IP}
      - STROOM_PORT=${STROOM_APP_PORT:-8080}
      - AUTH_SERVICE_HOST=${AUTH_SERVICE_HOST:-$HOST_IP}
    volumes:
      - ${NGINX_VOLUME_CERTS:-../volumes/nginx/certs}:/etc/nginx/certs:ro
      # nginx.conf.template - used to create the actual config when the container starts
      - ${NGINX_VOLUME_CONF:-../volumes/nginx/conf}:/etc/nginx/template:ro
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
