version: '2.1'
services:
    nginx:
        container_name: nginx
        image: "${STROOM_NGINX_DOCKER_REPO:-gchq/stroom-nginx}:${STROOM_NGINX_TAG:-v1.0.0_nginx-v1.13.8}"
        environment:
            - NGINX_ADVERTISED_HOST=${NGINX_HOST:-stroom-nginx}
        volumes:
            - "../../../certs:/etc/nginx/certs"
        ports:
            - "80:80"
            - "443:443"
