# Runs a Solr instance
version: '2.4'

services: 
  solr:
    image: "${SOLR_DOCKER_REPO:-solr}:${SOLR_TAG:-8.1.1}"
    hostname: solr
    ports:
      - 8983:8983
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
