version: '2.4'

services:

  stroom-annotations-ui:
    container_name: stroom-annotations-ui
    image: "${STROOM_ANNOTATIONS_UI_DOCKER_REPO:-gchq/stroom-annotations-ui}:${STROOM_ANNOTATIONS_UI_TAG:-v0.2.1-alpha.1}"
    environment:
      - ANNOTATIONS_UI_AUTHENTICATION_SERVICE_URL=https://${AUTH_SERVICE_HOST:-$HOST_IP}/authenticationService/v1
      - ANNOTATIONS_UI_AUTHORISATION_SERVICE_URL=https://${STROOM_AUTHORISATION_SERVICE_HOST:-$HOST_IP}/authorisationService/v1
      - ANNOTATIONS_UI_ADVERTISED_URL=${STROOM_ANNOTATIONS_UI_URL:-http://$HOST_IP:5001}
      - ANNOTATIONS_UI_APP_CLIENT_ID=stroom-annotations
      - ANNOTATIONS_UI_ANNOTATIONS_SERVICE_URL=https://${STROOM_ANNOTATIONS_SERVICE_HOST:-$HOST_IP}/annotationsService
      # The NGINX_xxx variables configure the NGINX server that serves the app
      - NGINX_HOST=${STROOM_ANNOTATIONS_UI_HOST:-$HOST_IP}
      - NGINX_HTTP_PORT=${STROOM_ANNOTATIONS_UI_HTTP_PORT:-5001}
      - NGINX_HTTPS_PORT=${STROOM_ANNOTATIONS_UI_HTTPS_PORT:-9444}
      - NGINX_SSL_CERTIFICATE=${NGINX_SSL_CERTIFICATE:-server.pem.crt}
      - NGINX_SSL_CERTIFICATE_KEY=${NGINX_SSL_CERTIFICATE_KEY:-server.unencrypted.key}
      - NGINX_SSL_CLIENT_CERTIFICATE=${NGINX_SSL_CLIENT_CERTIFICATE:-ca.pem.crt}
    volumes:
      # Shared certs volume: TODO: move it to the top level
      - ../../../dev-resources/certs/server:/etc/nginx/certs:ro
      # nginx.conf.template - used to create the actual config when the container starts
      - ../../../stroom-microservice-ui/template:/etc/nginx/template:ro
    ports:
      - 5001:5001
      - 9444:9444
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
