version: '2.4'

services: 

  stroom-proxy-remote:
    container_name: stroom-proxy-remote
    image: "${STROOM_PROXY_DOCKER_REPO:-gchq/stroom-proxy}:${STROOM_PROXY_TAG:-v6-LATEST}"
    environment:
      - CONTENT_SYNC_ENABLED=${STROOM_PROXY_REMOTE_CONTENT_SYNC_ENABLED:-false}
      - FORWARD_URL=${STROOM_PROXY_REMOTE_FORWARD_URL:-http://stroom-proxy-local:8090/stroom/datafeed}
      - FORWARDING_ENABLED=${STROOM_PROXY_REMOTE_FORWARDING_ENABLED:-true}
      #- JAVA_OPTS=${STROOM_PROXY_REMOTE_JAVA_OPTS:- -Xms50m -Xmx1024m }
      - JAVA_OPTS=${STROOM_PROXY_REMOTE_JAVA_OPTS:- -Xms50m -Xmx1024m -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=${STROOM_PROXY_REMOTE_DEBUG_PORT:-10767},suspend=n }
      - RECEIPT_POLICY_UUID=${STROOM_PROXY_REMOTE_RECEIPT_POLICY_UUID:-}
      - STORING_ENABLED=${STROOM_PROXY_REMOTE_STORING_ENABLED:-true}
      #- STROOM_PROXY_APP_PORT=${STROOM_PROXY_REMOTE_APP_PORT:-9090}
      - STROOM_PROXY_APP_PORT=8090
      #- STROOM_PROXY_ADMIN_PORT=${STROOM_PROXY_REMOTE_ADMIN_PORT:-9091}
      - STROOM_PROXY_ADMIN_PORT=8091
      - STROOM_PROXY_REMOTE_DEBUG_PORT=${STROOM_PROXY_REMOTE_DEBUG_PORT:-10767}
      - SYNC_API_KEY=${STROOM_PROXY_REMOTE_SYNC_API_KEY:-}
      - UPSTREAM_RULE_URL=${STROOM_PROXY_REMOTE_UPSTREAM_RULE_URL:-http://stroom-proxy-local:8090/api/ruleset/v1}
      - UPSTREAM_DICTIONARY_URL=${STROOM_PROXY_REMOTE_UPSTREAM_DICTIONARY_URL:-http://stroom-proxy-local:8090/api/dictionary/v1}
    ports:
      - "${STROOM_PROXY_REMOTE_APP_PORT:-9090}:${STROOM_PROXY_APP_PORT:-8090}"
      #- "${STROOM_PROXY_APP_PORT_HTTPS:-8543}:${STROOM_PROXY_APP_PORT_HTTPS:-8543}"
      - "${STROOM_PROXY_REMOTE_ADMIN_PORT:-9091}:${STROOM_PROXY_ADMIN_PORT:-8091}"
      - "${STROOM_PROXY_REMOTE_DEBUG_PORT:-10767}:${STROOM_PROXY_REMOTE_DEBUG_PORT:-10767}"
    healthcheck:
      test: curl --fail --silent --head --output /dev/null http://localhost:${STROOM_PROXY_ADMIN_PORT}/proxyAdmin/healthcheck || exit 1
      start_period: 30s 
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - type: volume
        source: stroom-proxy-remote_config
        target: /stroom-proxy/config
      - type: volume
        source: stroom-proxy-remote_content
        target: /stroom-proxy/content
      - type: volume
        source: stroom-proxy-remote_logs
        target: /stroom-proxy/logs
      - type: volume
        source: stroom-proxy-remote_repo
        target: /stroom-proxy/repo
    logging:
      options:
        max-size: "${STROOM_PROXY_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_PROXY_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
