version: "2.4"

services:
  stroom-auth-service:
    container_name: stroom-auth-service
    image: "${STROOM_AUTH_SERVICE_DOCKER_REPO:-gchq/stroom-auth-service}:${STROOM_AUTH_SERVICE_TAG:-v1.0-LATEST}"
    environment:
      - STROOM_UI=${STROOM_AUTH_STROOM_UI:-http://$HOST_IP:8099 }
      - ADVERTISED_HTTP_HOST=http://${STROOM_AUTH_SERVICE_HOST:-$HOST_IP}/authService
      - AUTH_UI=${STROOM_AUTH_UI_ACTIVE_SCHEME:-http}://${STROOM_AUTH_UI_URL:-$HOST_IP:5000}/login
      - OWN_PATH=${STROOM_AUTH_SERVICE:-authentication}
      - JAVA_OPTS=${STROOM_AUTH_SERVICE_JAVA_OPTS:- -Xms50m -Xmx1024m }
      - STROOM_AUTH_SERVICE_PORT=${STROOM_AUTH_SERVICE_PORT:-8099}
      - STROOM_AUTH_SERVICE_ADMIN_PORT=${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}
      - DB_USER=${STROOM_AUTH_DB_USERNAME:-authuser}
      - DB_PASSWORD=${STROOM_AUTH_DB_PASSWORD:-stroompassword1}
      - DB_URL=jdbc:mysql://${STROOM_AUTH_DB_HOST:-$HOST_IP}:${STROOM_AUTH_DB_PORT:-3307}/auth?useUnicode=yes&characterEncoding=UTF-8
      - JWS_ISSUER=stroom
      - ADMIN_CONTEXT_PATH=/authenticationServiceAdmin
      - APPLICATION_CONTEXT_PATH=${STROOM_AUTH_APPLICATION_CONTEXT_PATH:-/}
      - CERTIFICATE_DN_PATTERN=${STROOM_AUTH_CERTIFICATE_DN_PATTERN:-.*\((.*)\)}
      - CERTIFICATE_DN_CAPTURE_GROUP_INDEX=${STROOM_AUTH_CERTIFICATE_DN_CAPTURE_GROUP_INDEX:-1}
      - JWS_ALGORITHM=${STROOM_AUTH_JWS_ALGORITHM:-RS256}
      - JWS_REQUIRE_EXPIRATION_TIME=${STROOM_AUTH_JWS_REQUIRE_EXPIRATION_TIME:-false }
      - AUTHORISATION_SERVICE_URL=http://${STROOM_AUTHORISATION_SERVICE_HOST:-$HOST_IP}/authorisationService/v1
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PATH=/canManageUsers
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PERMISSION=Manage Users
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_USER_TOKEN=43200 # 43200 minutes = 30 days
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_API_TOKEN=525600 # 525600 minutes = 1 year
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_EMAIL_RESET_TOKEN=5 # Only 5 minutes
      - CHANGE_PASSWORD_URL=${STROOM_AUTH_UI_ACTIVE_SCHEME:-http}://${STROOM_AUTH_UI_URL:-$HOST_IP:5000}/changePassword
      - FORCE_PASSWORD_CHANGE_ON_FIRST_LOGIN=${STROOM_AUTH_FORCE_PASSWORD_CHANGE_ON_FIRST_LOGIN:-true}
      # There is an effective regex here: https://stackoverflow.com/questions/3802192/regexp-java-for-password-validation
      # The regex from there is too complicated and mucks up this yaml. If you want to use more complicated validation
      # then you'll have to set it in the env var file.
      - PASSWORD_COMPLEXITY_REGEX=${STROOM_AUTH_PASSWORD_COMPLEXITY_REGEX:-.*}
      - MINIMUM_PASSWORD_LENGTH=${STROOM_AUTH_MINIMUM_PASSWORD_LENGTH:-8}
      - SECONDS_BETWEEN_PASSWORD_INTEGRITY_CHECKS=${STROOM_AUTH_SECONDS_BETWEEN_PASSWORD_INTEGRITY_CHECKS:-3600}
      - REQUIRE_PASSWORD_CHANGE_AFTER_X_DAYS=${STROOM_AUTH_REQUIRE_PASSWORD_CHANGE_AFTER_X_DAYS:-30}
      - DISABLE_INACTIVE_ACCOUNT_AFTER_X_DAYS=${STROOM_AUTH_DISABLE_INACTIVE_ACCOUNT_AFTER_X_DAYS:-90}
      - DISABLE_INACTIVE_NEW_ACCOUNT_AFTER_X_DAYS=${STROOM_AUTH_DISABLE_INACTIVE_NEW_ACCOUNT_AFTER_X_DAYS:-30}
      - FAILED_LOGIN_LOCK_THRESHOLD=${STROOM_AUTH_FAILED_LOGIN_LOCK_THRESHOLD:-3}
      - ALLOW_PASSWORD_RESETS=${STROOM_AUTH_ALLOW_PASSWORD_RESETS:-false}
      - EMAIL_FROM_ADDRESS=${STROOM_AUTH_EMAIL_FROM_ADDRESS:-TODO}
      - EMAIL_FROM_NAME=${STROOM_AUTH_EMAIL_FROM_NAME:-Stroom User Accounts}
      - EMAIL_RESET_SUBJECT=${STROOM_AUTH_EMAIL_RESET_SUBJECT:-Password reset for Stroom}
      - EMAIL_RESET_TEXT=${STROOM_AUTH_EMAIL_RESET_TEXT:-A password reset has been requested for this email address. Please visit the following URL to reset your password -- %s.}
      - EMAIL_RESET_TOKEN_VALIDITY_IN_MINUTES=${STROOM_AUTH_EMAIL_RESET_TOKEN_VALIDITY_IN_MINUTES:-60}
      - EMAIL_RESET_URL=${STROOM_AUTH_EMAIL_RESET_URL:-http://$HOST_IP:5000/resetPassword/?token=%s}
      - EMAIL_SMTP_HOST=${STROOM_AUTH_EMAIL_SMTP_HOST:-$HOST_IP}
      - EMAIL_SMTP_PORT=${STROOM_AUTH_EMAIL_SMTP_PORT:-2525}
      - EMAIL_SMTP_TRANSPORT=${STROOM_AUTH_EMAIL_SMTP_TRANSPORT:-plain}
      - EMAIL_SMTP_USERNAME=${STROOM_AUTH_EMAIL_SMTP_USERNAME:-TODO}
      - EMAIL_SMTP_PASSWORD=${STROOM_AUTH_EMAIL_SMTP_PASSWORD:-TODO}
      - LOGS_EVENT_FEED_NAME=${STROOM_AUTH_LOGS_EVENT_FEED_NAME:-STROOM_AUTH-USER-EVENTS}
      - LOGS_ACCESS_FEED_NAME=${STROOM_AUTH_LOGS_ACCESS_FEED_NAME:-STROOM_AUTH-ACCESS-EVENTS}
      - LOGS_APP_FEED_NAME=${STROOM_AUTH_LOGS_APP_FEED_NAME:-STROOM_AUTH-APP-EVENTS}
      - LOGS_SYSTEM=${STROOM_AUTH_LOGS_SYSTEM:-StroomAuth}
      - LOGS_ENV=${STROOM_AUTH_LOGS_ENV:-Dev}
      - LOGS_STROOM_URL=${STROOM_AUTH_LOGS_STROOM_URL:-http://stroom:8080/stroom/datafeed}
      - LOGS_CRONTAB=${STROOM_AUTH_LOGS_CRONTAB:-* * * * *}
      - LOGS_MAX_SLEEP=${STROOM_LOGS_MAX_SLEEP:-10}
      - LOGS_SECURE=${STROOM_LOGS_SECURE:-true}
    ports:
      - "${STROOM_AUTH_SERVICE_PORT:-8099}:${STROOM_AUTH_SERVICE_PORT:-8099}"
      - "${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}:${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}"
    healthcheck:
      test: curl --fail --silent --head --output /dev/null http://localhost:${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}/authenticationServiceAdmin/healthcheck || exit 1
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - type: volume
        source: stroom-auth-service_logs
        target: /stroom-auth-service/logs
    logging:
      options:
        max-size: "${STROOM_AUTH_SERVICE_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_AUTH_SERVICE_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
