version: '2'

services:

  stroom-annotations-ui:
    container_name: stroom-annotations-ui
    image: gchq/stroom-annotations-ui:v0.1.5-alpha.2
    environment:
      - REACT_APP_STROOM_AUTH_SERVICE_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8096
      - REACT_APP_STROOM_UI_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8080
      - REACT_APP_LOGIN_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/authenticationService/v1/login
      - REACT_APP_AUTHENTICATION_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/authenticationService/v1
      - REACT_APP_AUTHORISATION_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/authorisationService/v1
      - REACT_APP_ANNOTATIONS_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/annotationsService/v1
      - REACT_APP_USER_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/userService/v1
      - REACT_APP_TOKEN_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/tokenService/v1
      - REACT_APP_STROOM_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/stroom
      - REACT_APP_ROOT_PATH=
    ports:
      - 5001:5000