version: '2.1'

services:

  stroom-annotations-ui:
    container_name: stroom-annotations-ui
    image: "gchq/stroom-annotations-ui:${STROOM_ANNOTATIONS_UI_TAG:-v0.1.5-alpha.4}"
    environment:
      - ANNOTATIONS_UI_AUTHENTICATION_SERVICE_URL=http://stroom-auth-service:8099/authentication/v1
      - ANNOTATIONS_UI_AUTHORISATION_SERVICE_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/api/authorisation/v1
      - ANNOTATIONS_UI_ADVERTISED_URL=http://stroom-annotations-ui:5001
      - ANNOTATIONS_UI_APP_CLIENT_ID=stroom-annotations
      - ANNOTATIONS_UI_ANNOTATIONS_SERVICE_URL=http://stroom-annotations-service:8199/annotationsService/annotations/v1
    ports:
      - 5001:5000

