version: '2'

services:

  stroom-auth-ui:
    container_name: stroom-auth-ui
    image: gchq/stroom-auth-ui:latest
    environment:
      - REACT_APP_STROOM_AUTH_SERVICE_URL=http://stroom-auth-service:8096
      - REACT_APP_STROOM_UI_URL=http://stroom:8080
    ports:
      - 5000:5000