version: '2'

services:

  stroom-auth-ui:
    container_name: stroom-auth-ui
    image: gchq/stroom-auth-ui:v0.1.1-alpha
    environment:
      - REACT_APP_STROOM_AUTH_SERVICE_URL=http://stroom-auth-service:8096
      - REACT_APP_STROOM_UI_URL=http://stroom:8080
      - REACT_APP_LOGIN_URL=http://localhost/authenticationService/v1/login
      - REACT_APP_AUTHENTICATION_URL=http://localhost/authenticationService/v1
      - REACT_APP_USER_URL=http://localhost/userService/v1
      - REACT_APP_STROOM_URL=http://localhost/stroom
      - REACT_APP_ROOT_PATH=
    ports:
      - 5000:5000