version: '2.1'

services: 

  stroom-db:
    image: "${MYSQL_DOCKER_REPO:-mysql}:5.6"
    container_name: stroom-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${STROOM_DB_ROOT_PASSWORD:-my-secret-pw}
      - MYSQL_USER=${STROOM_DB_USERNAME:-stroomuser}
      - MYSQL_PASSWORD=${STROOM_DB_PASSWORD:-stroompassword1}
      - MYSQL_DATABASE=stroom
    volumes:
      - ${STROOM_DB_DATA_VOLUME:-~/.stroom/db_data/stroom-db}:/var/lib/mysql
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
