version: '2.1'

services:

  stroom-auth-ui:
    container_name: stroom-auth-ui
    image: "gchq/stroom-auth-ui:${STROOM_AUTH_UI_TAG:-master-SNAPSHOT}"
    # All URLs are accessed from a browser, and so need to refer to the advertised host.
    environment:
      - AUTH_UI_AUTHENTICATION_SERVICE_URL=http://auth-service:8099/authentication/v1
      - AUTH_UI_USER_SERVICE_URL=http://auth-service:8099/user/v1
      - AUTH_UI_TOKEN_SERVICE_URL=http://auth-service:8099/token/v1
      - AUTH_UI_AUTHORISATION_SERVICE_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/api/authorisation/v1
      - AUTH_UI_STROOM_UI_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/stroom
      - AUTH_UI_ADVERTISED_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:5000
      - AUTH_UI_APP_CLIENT_ID=stroom-accounts
      - AUTH_UI_ROOT_PATH=
    ports:
      - 5000:5000
