version: '2.1'

services:

  stroom-auth-ui:
    container_name: stroom-auth-ui
    image: "${STROOM_AUTH_UI_DOCKER_REPO:-gchq/stroom-auth-ui}:${STROOM_AUTH_UI_TAG:-v0.1-LATEST}"
    # All URLs are accessed from a browser, and so need to refer to the advertised host.
    environment:
      # The AUTH_UI_xxx variables configure the app as loaded in the browser
      - AUTH_UI_AUTHENTICATION_SERVICE_URL=https://${AUTH_SERVICE_HOST:-$HOST_IP}/authenticationService/v1
      - AUTH_UI_USER_SERVICE_URL=https://${AUTH_SERVICE_HOST:-$HOST_IP}/userService/v1
      - AUTH_UI_TOKEN_SERVICE_URL=https://${AUTH_SERVICE_HOST:-$HOST_IP}/tokenService/v1
      - AUTH_UI_AUTHORISATION_SERVICE_URL=https://${STROOM_AUTHORISATION_SERVICE_HOST:-$HOST_IP}/authorisationService/v1
      - AUTH_UI_STROOM_UI_URL=https://${STROOM_HOST:-$HOST_IP}:8080/stroom
      - AUTH_UI_ADVERTISED_URL=${STROOM_AUTH_UI_URL:-http://$HOST_IP:5000}
      - AUTH_UI_APP_CLIENT_ID=stroom-accounts
      # The NGINX_xxx variables configure the NGINX server that serves the app
      - NGINX_HOST=${STROOM_AUTH_UI_HOST:-$HOST_IP}
      - NGINX_HTTP_PORT=${STROOM_AUTH_UI_HTTP_PORT:-5000}
      - NGINX_HTTPS_PORT=${STROOM_AUTH_UI_HTTPS_PORT:-9443}
      - NGINX_SSL_CERTIFICATE=${NGINX_SSL_CERTIFICATE:-server.pem.crt}
      - NGINX_SSL_CERTIFICATE_KEY=${NGINX_SSL_CERTIFICATE_KEY:-server.unencrypted.key}
      - NGINX_SSL_CLIENT_CERTIFICATE=${NGINX_SSL_CLIENT_CERTIFICATE:-ca.pem.crt}
    volumes:
      # Shared certs volume: TODO: move it to the top level
      - ${STROOM_AUTH_UI_VOLUME_CERTS:-./volumes/auth-ui/certs}:/etc/nginx/certs
      # nginx.conf.template - used to create the actual config when the container starts
      - ${STROOM_AUTH_UI_VOLUME_CONF:-./volumes/auth-ui/conf}:/etc/nginx/template
    ports:
      - 5000:5000
      - 9443:9443
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"