version: '2.1'

services:
    
  stroom:
    container_name: stroom
    image: "${STROOM_REPO:-gchq/stroom}:${STROOM_TAG:-master-SNAPSHOT}"
    environment:
      - STROOM_NODE=node1a
      - STROOM_RACK=rack
      - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
      - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
      - STROOM_JDBC_DRIVER_URL=jdbc:mysql://${STROOM_DB_HOST:-stroom-db}:${STROOM_DB_PORT:-3306}/stroom?useUnicode=yes&characterEncoding=UTF-8
      - STROOM_JDBC_DRIVER_USERNAME=stroomuser
      - STROOM_JDBC_DRIVER_PASSWORD=stroompassword1
      - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://${STROOM_STATS_DB_HOST:-stroom-stats-db}:${STROOM_STATS_DB_PORT:-3306}/statistics?useUnicode=yes&characterEncoding=UTF-8
      - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=stroomuser
      - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=stroompassword1
      # The browser is redirected to this URL so, like the AUTH UI URL, it needs to be the advertised host.
      - STROOM_AUTH_SERVICES_URL=http://${STROOM_AUTH_SERVICE_HOST:-stroom-auth-service}/authService
      - STROOM_AUTH_AUTHENTICATION_SERVICE_URL=http://${STROOM_AUTH_SERVICE_HOST:-stroom-auth-service}/authenticationService/v1
      - STROOM_AUTH_JWT_ISSUER=stroom
      - STROOM_AUTH_JWT_ENABLETOKENREVOCATIONCHECK=${ENABLE_TOKEN_REVOCATION_CHECK}
      - STROOM_USERS_UI_URL=https://${STROOM_AUTH_UI_HOST:-stroom-auth-ui}/users
      - STROOM_APIKEYS_UI_URL=https://${STROOM_AUTH_UI_HOST:-stroom-auth-ui}/tokens
      - STROOM_CHANGEPASSWORD_URL=https://${STROOM_AUTH_UI_HOST:-stroom-auth-ui}/changepassword
      - STROOM_ADVERTISED_URL=https://${NGINX_HOST:-stroom}/stroom/ui
      # This needs to be an API token issued for a user, i.e. for the admin user.
      # Without this Stroom won't be able to make calls to it's RemoteDataSources.
      - STROOM_SECURITY_API_TOKEN=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1NDQ4NjMwNDMsInN1YiI6InN0cm9vbVNlcnZpY2VVc2VyIiwiaXNzIjoic3Ryb29tIn0.gHJkpxeW5CjU_hBzuLhQd8Ot8XkLvhu45_-Ql4gOX96iNbl0AnKEwKu2QmMY3uVerGjYBHDczgKJlLVF_RQtFiwFLorT2P_Mv-9ShcCL0Ml-Tq-1i-_UnHMYHP5Nv-rP3ajUz-vTHwIYqi_WU-IEpIF56MCYBqeDkgQfe-I03VyfsLkWt-3f8L3AKESZirmqjPUB_SPi4vWGpyN28FuJe1KyqdCPo5QVKnrM_dpguE_aIj1Dy1sovmgO5WxFm3-hE7asW3WrnokSopNXQ1bJ3W77v4k1CnMpYDw5schQAKqUffPVGxNE6UxNunZTlRQJQqYihKkhpeiTiZMo9XCHGg
      - ADMIN_CONTEXT_PATH=/stroomAdmin
      - STROOM_LOGGING_LEVEL=INFO
      - STROOM_PLUGINS_LIB_DIR=/stroom/plugins
      - STROOM_CONNECTORS_KAFKA_DEFAULT_BOOTSTRAP_SERVERS=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      - STROOM_CONNECTORS_KAFKA_DEFAULT_CONNECTOR_VERSION=0.10.0.1
      - STROOM_SERVICE_DISCOVERY_ENABLED=${STROOM_SERVICE_DISCOVERY_ENABLED:-true}
      - STROOM_SERVICE_DISCOVERY_ZOOKEEPER_URL=${ZOOKEEPER_QUORUM:-zookeeper:2181}
        #expose this so we can set it from the shell's env vars
      - STROOM_DEVELOPMENT_MODE=${STROOM_DEVELOPMENT_MODE:-true}
      - STROOM_INTERNAL_STATISTICS_BENCHMARK_CLUSTER_DOC_REFS=${STROOM_INTERNAL_STATISTICS_BENCHMARK_CLUSTER_DOC_REFS:-docRef(StatisticStore,946a88c6-a59a-11e6-bdc4-0242ac110002,Benchmark-Cluster Test),docRef(StroomStatsStore,2503f703-5ce0-4432-b9d4-e3272178f47e,Benchmark-Cluster Test)}
      - STROOM_INTERNAL_STATISTICS_CPU_DOC_REFS=${STROOM_INTERNAL_STATISTICS_CPU_DOC_REFS:-docRef(StatisticStore,af08c4a7-ee7c-44e4-8f5e-e9c6be280434,CPU),docRef(StroomStatsStore,1edfd582-5e60-413a-b91c-151bd544da47,CPU)}
      - STROOM_INTERNAL_STATISTICS_EVENTS_PER_SECOND_DOC_REFS=${STROOM_INTERNAL_STATISTICS_EVENTS_PER_SECOND_DOC_REFS:-docRef(StatisticStore,a9936548-2572-448b-9d5b-8543052c4d92,EPS),docRef(StroomStatsStore,cde67df0-0f77-45d3-b2c0-ee8bb7b3c9c6,EPS)}
      - STROOM_INTERNAL_STATISTICS_HEAP_HISTOGRAM_BYTES_DOC_REFS=${STROOM_INTERNAL_STATISTICS_HEAP_HISTOGRAM_BYTES_DOC_REFS:-docRef(StatisticStore,934a1600-b456-49bf-9aea-f1e84025febd,Heap Histogram Bytes),docRef(StroomStatsStore,b0110ab4-ac25-4b73-b4f6-96f2b50b456a,Heap Histogram Bytes)}
      - STROOM_INTERNAL_STATISTICS_HEAP_HISTOGRAM_INSTANCES_DOC_REFS=${STROOM_INTERNAL_STATISTICS_HEAP_HISTOGRAM_INSTANCES_DOC_REFS:-docRef(StatisticStore,e4f243b8-2c70-4d6e-9d5a-16466bf8764f,Heap Histogram Instances),docRef(StroomStatsStore,bdd933a4-4309-47fd-98f6-1bc2eb555f20,Heap Histogram Instances)}
      - STROOM_INTERNAL_STATISTICS_MEMORY_DOC_REFS=${STROOM_INTERNAL_STATISTICS_MEMORY_DOC_REFS:-docRef(StatisticStore,77c09ccb-e251-4ca5-bca0-56a842654397,Memory),docRef(StroomStatsStore,d8a7da4f-ef6d-47e0-b16a-af26367a2798,Memory)}
      - STROOM_INTERNAL_STATISTICS_METADATA_STREAM_SIZE_DOC_REFS=${STROOM_INTERNAL_STATISTICS_METADATA_STREAM_SIZE_DOC_REFS:-docRef(StatisticStore,946a8814-a59a-11e6-bdc4-0242ac110002,Meta Data-Stream Size),docRef(StroomStatsStore,3b25d63b-5472-44d0-80e8-8eea94f40f14,Meta Data-Stream Size)}
      - STROOM_INTERNAL_STATISTICS_META_DATA_STREAMS_RECEIVED_DOC_REFS=${STROOM_INTERNAL_STATISTICS_META_DATA_STREAMS_RECEIVED_DOC_REFS:-docRef(StatisticStore,946a87bc-a59a-11e6-bdc4-0242ac110002,Meta Data-Streams Received),docRef(StroomStatsStore,5535f493-29ae-4ee6-bba6-735aa3104136,Meta Data-Streams Received)}
      - STROOM_INTERNAL_STATISTICS_PIPELINE_STREAM_PROCESSOR_DOC_REFS=${STROOM_INTERNAL_STATISTICS_PIPELINE_STREAM_PROCESSOR_DOC_REFS:-docRef(StatisticStore,946a80fc-a59a-11e6-bdc4-0242ac110002,PipelineStreamProcessor),docRef(StroomStatsStore,efd9bad4-0bab-460f-ae98-79e9717deeaf,PipelineStreamProcessor)}
      - STROOM_INTERNAL_STATISTICS_STREAM_TASK_QUEUE_SIZE_DOC_REFS=${STROOM_INTERNAL_STATISTICS_STREAM_TASK_QUEUE_SIZE_DOC_REFS:-docRef(StatisticStore,946a7f0f-a59a-11e6-bdc4-0242ac110002,Stream Task Queue Size),docRef(StroomStatsStore,4ce8d6e7-94be-40e1-8294-bf29dd089962,Stream Task Queue Size)}
      - STROOM_INTERNAL_STATISTICS_VOLUMES_DOC_REFS=${STROOM_INTERNAL_STATISTICS_VOLUMES_DOC_REFS:-docRef(StatisticStore,ac4d8d10-6f75-4946-9708-18b8cb42a5a3,Volumes),docRef(StroomStatsStore,60f4f5f0-4cc3-42d6-8fe7-21a7cec30f8e,Volumes)}

    ports:
      - 8080:8080
      - 8081:8081
