version: '2.1'

services:

  stroom-query-elastic-service:
    container_name: stroom-query-elastic-service
    image: "${STROOM_QUERY_ELASTIC_SERVICE_DOCKER_REPO:-gchq/stroom-query-elastic-svc}:${STROOM_ELASTIC_SERVICE_TAG:-v0.0.2-alpha.3}"
    environment:
      - ELASTIC_CLUSTER_NAME=${ELASTIC_CLUSTER_NAME:-docker-cluster}
      - ELASTIC_TRANSPORT_HOSTS=${ELASTIC_HOST:-elasticsearch}:9300
      - AUTHORISATION_SERVICE_URL=http://${STROOM_AUTHORISATION_SERVICE_HOST:-stroom}:8080/api/authorisation/v1
      - AUTHORISATION_SERVICE_IS_AUTHORISED_PATH=/isAuthorised
    ports:
      - 8299:8299
      - 8300:8300
    entrypoint: ./wait-for-it_busybox.sh elasticsearch:9300 -- java -jar stroom-query-elastic-all.jar server config.yml
