version: '2.1'

services: 

  stroom-auth-db:
    image: "${MARIADB_DOCKER_REPO:-mariadb}:10.3.0"
    container_name: stroom-auth-db
    ports:
        # Expose mysql on 3309 to the host so as not to conflict with stroom-db or stroom-stats-db
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=stroomuser
      - MYSQL_PASSWORD=stroompassword1
      - MYSQL_DATABASE=auth
