version: '2.1'

services: 

  stroom-stats:
    container_name: stroom-stats
    image: "${STROOM_STATS_DOCKER_REPO:-gchq/stroom-stats}:${STROOM_STATS_TAG:-master-SNAPSHOT}"
    environment:
      - STATS_DB_USER=stroomuser
      - STATS_DB_PASSWORD=stroompassword1
      - STATS_DB_URL=jdbc:mysql://${STROOM_DB_HOST:-stroom-db}/stroom?useUnicode=yes&characterEncoding=UTF-8
      # quorum string of the form along the lines of
      # host1:2181
      # host1:2181/myChRoot
      # host1:2181,host2:2181,host3:2181
      # host1:2181,host2:2181,host3:2181/myChRoot
      - STATS_ZK_QUORUM=${ZOOKEEPER_QUORUM:-zookeeper:2181}

      # The following env vars set the values used to seed an empty zookeeper. 
      # Once ZK has been seeded, changing these values has no affect as stroom-stats 
      # will always use the values obtained from ZK.
      # Changing the value in ZK requires the ZK CLI or some other tool.
      #~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      - STATS_KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP_SERVERS:-kafka:9092}
      # Comma delimited list of hosts in the ZK quorum (no port or chroot), e.g. host1,host2,host3
      - STATS_HBASE_ZK_QUORUM_HOSTS=${HBASE_ZOOKEEPER_QUORUM_HOSTS:-zookeeper}
      - ADMIN_CONTEXT_PATH=/statsAdmin
      - AUTHENTICATION_SERVICE_URL=http://${STROOM_AUTH_SERVICE_HOST:-stroom-auth-service}/authService
      - AUTHORISATION_SERVICE_URL=http://${STROOM_HOST:-stroom}:8080/api/authorisation/v1
    ports:
      - 8086:8086 # app
      - 8087:8087 # admin
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
