version: '2.1'

services: 

  stroom-all-dbs:
    image: "${MYSQL_DOCKER_REPO:-mysql}:5.6"
    container_name: stroom-all-dbs
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${STROOM_DB_ROOT_PASSWORD:-my-secret-pw}
      #- STROOM_DB_USERNAME=${STROOM_DB_USERNAME:-stroomuser}
      #- STROOM_DB_PASSWORD=${STROOM_DB_PASSWORD:-stroompassword1}
      #- MYSQL_DATABASE=stroom
    command: mysqld
    entrypoint:
      #sh -c "/usr/local/bin/docker-entrypoint.sh mysqld"
      sh -c "
          echo > /docker-entrypoint-initdb.d/init.sql;
          echo \"SELECT USER();\" >> /docker-entrypoint-initdb.d/init.sql;
          echo \"SELECT DATABASE();\" >> /docker-entrypoint-initdb.d/init.sql;
          echo \"CREATE DATABASE IF NOT EXISTS stroom;\" >> /docker-entrypoint-initdb.d/init.sql;
          echo \"show databases;\" >> /docker-entrypoint-initdb.d/init.sql;
          echo 'CREATE USER \"stroomuser\"@\"%\" IDENTIFIED BY \"stroompassword1\";' >> /docker-entrypoint-initdb.d/init.sql;
          echo \"SELECT User, Host FROM mysql.user;\" >> /docker-entrypoint-initdb.d/init.sql;
          cat /docker-entrypoint-initdb.d/init.sql;
          /usr/local/bin/docker-entrypoint.sh mysqld"


      #- /bin/sh
      #- -c
      #- |
          #echo > /docker-entrypoint-initdb.d/init.sql;
          #echo "CREATE DATABASE IF NOT EXISTS 'stroom';" >> /docker-entrypoint-initdb.d/init.sql;
          #echo "CREATE USER '${STROOM_DB_USERNAME:-stroomuser}'@'%' IDENTIFIED BY '${STROOM_DB_PASSWORD:-stroompassword1}';" >> /docker-entrypoint-initdb.d/init.sql;
          #echo "CREATE DATABASE IF NOT EXISTS 'stroom-statistics';" >> /docker-entrypoint-initdb.d/init.sql;
          #echo "CREATE USER '${STROOM_STATS_DB_USERNAME:-stroomuser}'@'%' IDENTIFIED BY '${STROOM_STATS_DB_PASSWORD:-stroompassword1}';" >> /docker-entrypoint-initdb.d/init.sql;
          #/usr/local/bin/docker-entrypoint.sh
    volumes:
      - ${STROOM_DB_DATA_VOLUME:-../volumes/stroom-all-dbs}:/var/lib/mysql
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"

