version: '2.1'

services: 

  stroom-annotations-db:
    image:  "${MARIADB_DOCKER_REPO:-mariadb}:10.3.0"
    container_name: stroom-annotations-db
    ports:
        # Expose mysql on 3310 to the host so as not to conflict with stroom-db, stroom-stats-db, stroom-auth-db
      - "3310:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${STROOM_ANNOTATIONS_DB_ROOT_PASSWORD:-my-secret-pw}
      - MYSQL_USER=${STROOM_ANNOTATIONS_DB_USERNAME:-stroomuser}
      - MYSQL_PASSWORD=${STROOM_ANNOTATIONS_DB_PASSWORD:-stroompassword1}
      - MYSQL_DATABASE=annotations
    volumes:
      - ${STROOM_ANNOTATIONS_DB_DATA_VOLUME:-~/.stroom/db_data/stroom-annotations-db}:/var/lib/mysql
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"