version: '2.1'

services: 

  stroom-auth-db:
    image: "${MARIADB_DOCKER_REPO:-mariadb}:10.3.0"
    container_name: stroom-auth-db
    ports:
        # Expose mysql on 3309 to the host so as not to conflict with stroom-db or stroom-stats-db
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${STROOM_AUTH_DB_ROOT_PASSWORD:-my-secret-pw}
      - MYSQL_USER=${STROOM_AUTH_DB_USERNAME:-stroomuser}
      - MYSQL_PASSWORD=${STROOM_AUTH_DB_PASSWORD:-stroompassword1}
      - MYSQL_DATABASE=auth
    volumes:
      - ${STROOM_AUTH_DB_DATA_VOLUME:-~/.stroom/db_data/stroom-auth-db}:/var/lib/mysql
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"