version: '2'

services:

  stroom-auth-service:
    container_name: stroom-auth-service
    image: gchq/stroom-auth-service:v0.1.1-alpha
    environment:
      - DB_USER=stroomuser
      - DB_PASSWORD=stroompassword1
      - DB_URL=jdbc:mariadb://stroom-auth-db/auth
      - JWS_VERIFICATION_KEY={"kty":"RSA","kid":"k1","n":"uMF7JkZQDWvC9N0T1sw__7Tdaq0L34ghFBrKq7CkW-LiibQXh3eXBJtNPriDZ7QT4wA23jDF6Bq28RhEyWSssCqrm1Fjvq2ck5dd1shrqR-9WXBs0T1gXi4Mbne3aiWSWFHyW17qjEFoQfx9tLAX9eJYR56KpEu7Au6PAL_9ThQFlQy9wx5Dss8SQy6uwA9qw9A9lCGJKDhRwwBlXZ_5mJSWqqjNSz7ptIKAWvjOVTG8MmgOKqme9RLnWpQnNRf6h9ILK4wixAYLMQpIRphc9tFlZdhiy2yqcdiAEktCF7U0ZcnY3fN_-dw-VEHaCdUoBAPNqBsDPx9ewB8-wtyApQ","e":"AQAB","d":"b22RvoXNpiqGDHSBkJzjRG9q0vnHHWvWt29pKJ-CoUB3bKHHRxajaE3aCqfx6Mu86r2oWd2EnvXtu_7tDaHAXQd_NE-kHs5KjuFN4UpDVF8mLhkWKCQiSOrw6Hcfkc9TMh1KVD0srKaOIK4Nirph2RRINfmymGBsS9phOQyR01JNInQuDYNSgoDT-Uv1PjzHwD3AuJgiDV37OlASbAGGsb3LQQNUAuBIU6Hqo_hb7RZmi7P5QJnvsiMRr99TlFBoRfVrrFz4TCxQ24FidHGdSbCRW3vMku16zFYdoH1YZzNhkH0SzMunI2Gb2kOok7HSnY40vG9d0dXR7pxg6_2niQ","p":"5_w4aycxflrmrrm1lJjRU0MCvuQA5vY563E-iUKJvALh0WUOgyD_POsMWCYhQtk0nsCk6cMOakGwEauDNgNHgqXU7wA5VyRozZQI6ksf3e_FIqbuf37xfRVEV7XzGLq0l-g0bjG5DDGQW6Nv_61JDmyp-e_Yl-7rZbFNNKNk2Wc","q":"y-GlO8LXW8ymJDuBopC5BUVcwRx9rKOYgOyHu5Ds2X9w6JdB_fVRnua_cjkzaWhCKNfBOAnapnHms9SMCvYf69cSJh5xh5-IU7ngiw_EtBBMMUIZY1OQ_h8VIslrZEkEO7qQia8txW8_zgssbmyYFHc1O0QQ3tMm-2ZRwEkb8hM","dp":"VzHlHtlvb_fIxxnEV2MNIseIK6nVcPpRkN5SzBK3ZHSM3kCmsMDhTstmK2fBjrfHYHg2RCrtqyCfhjS6L74Rzdh47ZBe_RMRVVvz8eRkyO2LYlfuQvu61vH8ax9XjQ74PDSqKFUGIcAra1ZGDYrbb9GGHgx5k7nYvrNiuotDp7c","dq":"FpUQszTam71oLZ01t6bmB3JuWqloNiYMr0MDqb_crB6Uh_6w_Ysdlkcir2ksi6FTqqhzK1zUDhmRnxuMw24NjRbOWNCIbKg79mIhP-XoOLWRaudSXpET_0G8GpVKwtnfkSoR9l4j6LlwzMaqDjUTBzlI-R6J69RhffkQVwcCBGc","qi":"hnETo3IUbiqhIzvmRUUBAjD3IgFxjhNEGCQ7jTtGAcghowFtl_AKg6R80IAsA1EJNBcii7vUE3GePiFCkgGUfQrm3P-ovmI4rmD7xJcpZpnNyYVLJQWYlu4gOow__R_uLffmHYQIakjPe7BTEDqxl1VVGP1k3sm1avI4xF2QvdA"}
      - JWS_ISSUER=stroom
      - ADMIN_CONTEXT_PATH=/authenticationServiceAdmin
      - ADVERTISED_HTTP_HOST=http://${STROOM_RESOURCES_ADVERTISED_HOST}
      - AUTH_UI=http://${STROOM_RESOURCES_ADVERTISED_HOST}:5000/login
      - AUTHORISATION_SERVICE_URL=http://stroom:8080/api/authorisation/v1
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PATH=/canManageUsers
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PERMISSION=Manage Users
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_USER_TOKEN=43200 # 43200 minutes = 30 days
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_API_TOKEN=525600 # 525600 minutes = 1 year
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_EMAIL_RESET_TOKEN=5 # Only 5 minutes
    ports:
      - 8099:8099
      - 8100:8100
    entrypoint: ./wait-for-it_busybox.sh stroom-auth-db:3306 -- java -jar stroom-auth-service-all.jar server config.yml
