version: "2.4"

services:
  stroom-auth-service:
    container_name: stroom-auth-service
    image: "${STROOM_AUTH_SERVICE_DOCKER_REPO:-gchq/stroom-auth-service}:${STROOM_AUTH_SERVICE_TAG:-v1.0-LATEST}"
    environment:
      - JAVA_OPTS=${STROOM_AUTH_SERVICE_JAVA_OPTS:- -Xms50m -Xmx1024m }
      - STROOM_AUTH_SERVICE_PORT=${STROOM_AUTH_SERVICE_PORT:-8099}
      - STROOM_AUTH_SERVICE_ADMIN_PORT=${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}
      - DB_USER=${STROOM_AUTH_DB_USERNAME:-authuser}
      - DB_PASSWORD=${STROOM_AUTH_DB_PASSWORD:-stroompassword1}
      - DB_URL=jdbc:mysql://${STROOM_AUTH_DB_HOST:-$HOST_IP}:${STROOM_AUTH_DB_PORT:-3307}/auth?useUnicode=yes&characterEncoding=UTF-8
      - JWS_ISSUER=stroom
      - ADMIN_CONTEXT_PATH=/authenticationServiceAdmin
      - ADVERTISED_HTTP_HOST=http://${AUTH_SERVICE_HOST:-$HOST_IP}/authService
      - AUTH_UI=${STROOM_AUTH_UI_ACTIVE_SCHEME:-http}://${STROOM_AUTH_UI_URL:-$HOST_IP:5000}/login
      - CHANGE_PASSWORD_URL=${STROOM_AUTH_UI_ACTIVE_SCHEME:-http}://${STROOM_AUTH_UI_URL:-$HOST_IP:5000}/changePassword
      - AUTHORISATION_SERVICE_URL=http://${STROOM_AUTHORISATION_SERVICE_HOST:-$HOST_IP}/authorisationService/v1
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PATH=/canManageUsers
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PERMISSION=Manage Users
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_USER_TOKEN=43200 # 43200 minutes = 30 days
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_API_TOKEN=525600 # 525600 minutes = 1 year
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_EMAIL_RESET_TOKEN=5 # Only 5 minutes
      - FORCE_PASSWORD_CHANGE_ON_FIRST_LOGIN=${STROOM_AUTH_FORCE_PASSWORD_CHANGE_ON_FIRST_LOGIN:-true}
      - EMAIL_FROM_ADDRESS=${STROOM_AUTH_EMAIL_FROM_ADDRESS:-TODO}
      - EMAIL_FROM_NAME=${STROOM_AUTH_EMAIL_FROM_NAME:-Stroom User Accounts}
      - EMAIL_RESET_SUBJECT=${STROOM_AUTH_EMAIL_RESET_SUBJECT:-Password reset for Stroom}
      - EMAIL_RESET_TEXT=${STROOM_AUTH_EMAIL_RESET_TEXT:-A password reset has been requested for this email address. Please visit the following URL to reset your password -- %s.}
      - EMAIL_RESET_TOKEN_VALIDITY_IN_MINUTES=${STROOM_AUTH_EMAIL_RESET_TOKEN_VALIDITY_IN_MINUTES:-60}
      - EMAIL_SMTP_HOST=${STROOM_AUTH_EMAIL_SMTP_HOST:-TODO}
      - EMAIL_SMTP_PORT=${STROOM_AUTH_EMAIL_SMTP_PORT:-587}
      - EMAIL_SMTP_TRANSPORT=${STROOM_AUTH_EMAIL_SMTP_TRANSPORT:-TLS}
      - EMAIL_SMTP_USERNAME=${STROOM_AUTH_EMAIL_SMTP_USERNAME:-TODO}
      - EMAIL_SMTP_PASSWORD=${STROOM_AUTH_EMAIL_SMTP_PASSWORD:-TODO}
      - OWN_PATH=${STROOM_AUTH_SERVICE:-authentication}
      - LOGS_EVENT_FEED_NAME=${STROOM_AUTH_LOGS_EVENT_FEED_NAME:-STROOM_AUTH-USER-EVENTS}
      - LOGS_ACCESS_FEED_NAME=${STROOM_AUTH_LOGS_ACCESS_FEED_NAME:-STROOM_AUTH-ACCESS-EVENTS}
      - LOGS_APP_FEED_NAME=${STROOM_AUTH_LOGS_APP_FEED_NAME:-STROOM_AUTH-APP-EVENTS}
      - LOGS_SYSTEM=${STROOM_AUTH_LOGS_SYSTEM:-StroomAuth}
      - LOGS_ENV=${STROOM_AUTH_LOGS_ENV:-Dev}
      - LOGS_STROOM_URL=${STROOM_AUTH_LOGS_STROOM_URL:-http://stroom:8080/stroom/datafeed}
      - LOGS_CRONTAB=${STROOM_AUTH_LOGS_CRONTAB:-* * * * *}
      - LOGS_MAX_SLEEP=${STROOM_LOGS_MAX_SLEEP:-10}
      - LOGS_SECURE=${STROOM_LOGS_SECURE:-true}
    ports:
      - "${STROOM_AUTH_SERVICE_PORT:-8099}:${STROOM_AUTH_SERVICE_PORT:-8099}"
      - "${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}:${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}"
    healthcheck:
      test: curl --fail --silent --head --output /dev/null http://localhost:${STROOM_AUTH_SERVICE_ADMIN_PORT:-8100}/authenticationServiceAdmin/healthcheck || exit 1
      start_period: 1m
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - type: volume
        source: stroom-auth-service_logs
        target: /stroom-auth-service/logs
    logging:
      options:
        max-size: "${STROOM_AUTH_SERVICE_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_AUTH_SERVICE_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
