version: '2'

services:

  stroom-auth-service:
    container_name: stroom-auth-service
    image: gchq/stroom-auth-service:v0.1.1-alpha
    environment:
      - DB_USER=stroomuser
      - DB_PASSWORD=stroompassword1
      - DB_URL=jdbc:mariadb://stroom-auth-db/auth
      - JWS_VERIFICATION_KEY='{"kty":"RSA","n":"j3E8a1gLYvKZK1hQ-S1pnNVaejpZse4N0sj-6biWC-c2LoSwQyYi_TVeBWhGY7fEhkv-DFKaGbnSavJbEpAwpFj045sRDZqp3Rge6amAYYn_ckvTAt-3Ev9ojLTFaA_IWJ49k1JCfGJKZwov7bXieQpZlZaPG6ABaAunOuxAzwhb9A9QYG3mD6kPh4bpCJIFWKN_ajSIIgKOYViLlxy7hjyHtQIntJMT6bdhWu5nzDil_Y85Ypid50gM9HmSQ7XeE7JXUOQ4gIRhBxPt69PPikSvQkuPUgmx2571kiGBIyUHbrviY10nxVudvB8EunpTNjB1NRl354UKFUF-2X-35Q","e":"AQAB","d":"WH-ymT_e9pNasQVyH-pGyL5Rbivl_wMygCQGMkjyOjHSmey_mw5CdBqjAY8OLqPImlr0SMIF1W1yRw1z5wYTHLLNlEetw8jymDgzilJLpOIxOmFRtOo114DBDl7RlJx4LUSkFOqhnoA-C0ibvXuEWM1r7ADSFmcntvvJl27_pTtCy7o7TLl0e5oFIr-vh0lEPAOKC0aYlz-EotWvThi4A9mMo6KlZS8EB1CC_VtqwG1MyBZlG_nPO6dKMFJwl4_xrwirAZ0w5IOU6GW7LR1uvaOW4_SCTk6f5cCyZIeq7S7WAMRnrrWJ4DS9vHEQVPxnLI_RfjjqLqBytIcr3vKC2Q","p":"2Ng_72XfKWj0KfV3NM-yp17iUqbjOsOXpEAIzj_AzyA3YsFDKZlwkeuDfjb1xinasvTMk-WCkk7t2Yhp2TdysykP9A9zsrgB3pCHxkOHfB1cm2hMDm7ekw87Eqgoaz0gjVJUW1D95QvyXRSkxlA54Ns7izaOicyunHxKl7CFpRs","q":"qVfs9v_SB_L1KuF9G3ENLvbBRpoo-P-zW6xrv5i5K5GVDUP7G6_axDQkWStmzt23YLJBLSQMqtSy9EA08fQi_yk5L74J01s0AU348S1xD5992PkqH8kKIgZk0o8K2si3u-vKQVGtbFkOs90i99vRa3-sBxe9HAW5nLv29ri-5v8","dp":"pgknI2KIdoezdTFL3ncuX3OKrii1ErjTMuQJGgu80ZvkbMx4ZbDkfgasP4dLtzkzCRXiU1hIG0kuXANUsQsA22gUnBb8yxqT69wU6l2orwM4dpJsshx4dngSDl4N3NcIRs2EZAtm7Oux303AQU0KlD6poBXdHGxKQu30m6OBIYM","dq":"hWvsHLN0FKU8uttMCbnprC3oG6tMStqTws-3WQ6IHiamq_v6tVa5Y0q9tK-4YZZYa8wmA93aSSIqGL0ZueQjSqx9DPuKnEbIU5rOX57w7GE58yBlKwPnguVMvITNBZGNCXd-NDaZD7ufFOFPMr-zYSIHNNNkQNbV5gJGUx898Zs","qi":"kIGpHgfa6O5NTa7fGG3YkqBtV0buBnvmrvnXAxGVFQkOeed6jpIRYwEsvMp-uPx90NkRY2lOzkXZMhhc2iMRD4aewwpbnrx2rNUacryXw4j9hxsrh3Jl4yUsHRcbNnRrAlu8Lwu1h9lqjTY93G5kdHOooPOs0SIYGvm0D76H73s"}'
      - JWS_ISSUER=stroom
      - ADMIN_CONTEXT_PATH=/authenticationServiceAdmin
      - ADVERTISED_HTTP_HOST=http://${STROOM_RESOURCES_ADVERTISED_HOST}
      - AUTH_UI=http://${STROOM_RESOURCES_ADVERTISED_HOST}:5000/login
      - AUTHORISATION_SERVICE_URL=http://stroom:8080/api/authorisation/v1
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PATH=/canManageUsers
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PERMISSION=Manage Users
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_USER_TOKEN=43200 # 43200 minutes = 30 days
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_API_TOKEN=525600 # 525600 minutes = 1 year
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_EMAIL_RESET_TOKEN=5 # Only 5 minutes
    ports:
      - 8099:8099
      - 8100:8100
    entrypoint: ./wait-for-it_busybox.sh stroom-auth-db:3306 -- java -jar stroom-auth-service-all.jar server config.yml
