version: '2.1'

services: 

    stroom-stats:
        container_name: stroom-stats
        image: "${STROOM_STATS_DOCKER_REPO:-gchq/stroom-stats}:${STROOM_STATS_TAG:-master-SNAPSHOT}"
        environment:
            - STATS_DB_USER=stroomuser
            - STATS_DB_PASSWORD=stroompassword1
            - STATS_DB_URL=jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8
            - STATS_ZK_QUORUM=zookeeper:2181
            # The below two values change the default properties - they don't actually set them in ZK!
            # That is, once these have been set changing the below won't change them. You'd need to do that directly
             # on zk, using the CLI or some GUI.
            - STATS_KAFKA_BOOTSTRAP=kafka:9092
            - STATS_HBASE_ZK_QUORUM=zookeeper:2181
            - ADMIN_CONTEXT_PATH=/statsAdmin
        ports:
            - 8086:8086 # app
            - 8087:8087 # admin
