version: '2.1'

services: 

  stroom-stats-db:
    image: mysql:5.6
    container_name: stroom-stats-db
    ports:
        #expose mysql on 3307 to the host so as not to conflict with stroom-db
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=stroomuser
      - MYSQL_PASSWORD=stroompassword1
      - MYSQL_DATABASE=statistics
