#Runs the latest build of stroom from dockerhub 
version: '2.1'

services: 

    stroom:
        container_name: stroom
        image: "gchq/stroom:${STROOM_TAG:-master-SNAPSHOT}"
        environment:
            - STROOM_NODE=node1a
            - STROOM_RACK=rack
            - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
            - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
            - STROOM_JDBC_DRIVER_URL=jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://stroom-stats-db/statistics?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=stroompassword1
            # The browser is redirected to this URL so, like the AUTH UI URL, it needs to be the advertised host.
            - STROOM_AUTH_SERVICE_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8099
            - STROOM_AUTH_UI_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:5000
            - STROOM_AUTH_JWT_ISSUER=stroom
            - STROOM_AUTH_JWT_ENABLETOKENREVOCATIONCHECK=${ENABLE_TOKEN_REVOCATION_CHECK}
            - STROOM_ADVERTISED_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8080
            # This needs to be an API token issued for a user, i.e. for the admin user. 
            # Without this Stroom won't be able to make calls to it's RemoteDataSources.
            - STROOM_SECURITY_API_TOKEN=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsImlzcyI6InN0cm9vbSJ9.NLTH0YNedtKsco0E6jWTcPYV3AW2mLlgLf5TVxXVa-I
            - ADMIN_CONTEXT_PATH=/stroomAdmin
            - STROOM_LOGGING_LEVEL=INFO
            - STROOM_PLUGINS_LIB_DIR=/stroom/plugins
            - STROOM_CONNECTORS_KAFKA_DEFAULT_BOOTSTRAP_SERVERS=kafka:9092
            - STROOM_CONNECTORS_KAFKA_DEFAULT_CONNECTOR_VERSION=0.10.0.1
            - STROOM_SERVICE_DISCOVERY_ZOOKEEPER_URL=zookeeper:2181
              #expose this so we can set it from the shell's env vars
            - STROOM_DEVELOPMENT_MODE=${STROOM_DEVELOPMENT_MODE:-true}
        ports:
            - 8080:8080
            - 8081:8081

