version: '2.1'

services:

  stroom-auth-ui:
    container_name: stroom-ui
    image: "${STROOM_UI_DOCKER_REPO:-gchq/stroom-auth}:${STROOM_UI_TAG:-v1.0-LATEST}"
    # All URLs are accessed from a browser, and so need to refer to the advertised host.
    environment:
      # The AUTH_UI_xxx variables configure the app as loaded in the browser
      - STROOM_UI_AUTHENTICATION_SERVICE_URL=https://${AUTH_SERVICE_HOST:-$HOST_IP}/authenticationService/v1
      - STROOM_UI_AUTHORISATION_SERVICE_URL=https://${STROOM_AUTHORISATION_SERVICE_HOST:-$HOST_IP}/authorisationService/v1
      - STROOM_UI_ADVERTISED_URL=${STROOM_AUTH_UI_URL:-https://$HOST_IP:9443}
      - STROOM_UI_APP_CLIENT_ID=stroom-ui
      # The NGINX_xxx variables configure the NGINX server that serves the app
      - NGINX_HOST=${STROOM_AUTH_UI_HOST:-$HOST_IP}
      - NGINX_HTTP_PORT=${STROOM_AUTH_UI_HTTP_PORT:-5000}
      - NGINX_HTTPS_PORT=${STROOM_AUTH_UI_HTTPS_PORT:-9443}
      - NGINX_SSL_CERTIFICATE=${NGINX_SSL_CERTIFICATE:-server.pem.crt}
      - NGINX_SSL_CERTIFICATE_KEY=${NGINX_SSL_CERTIFICATE_KEY:-server.unencrypted.key}
      - NGINX_SSL_CLIENT_CERTIFICATE=${NGINX_SSL_CLIENT_CERTIFICATE:-ca.pem.crt}
    volumes:
      # Shared certs volume: TODO: move it to the top level
      - ${STROOM_UI_VOLUME_CERTS:-../volumes/stroom-ui/certs}:/etc/nginx/certs
      # nginx.conf.template - used to create the actual config when the container starts
      - ${STROOM_UI_VOLUME_CONF:-../volumes/stroom-ui/conf}:/etc/nginx/template
    ports:
      - 5000:5000
      - 9443:9443
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"