#Runs the latest build of stroom from dockerhub 
version: '2'

services: 

    stroom:
        container_name: stroom
        image: gchq/stroom:auth_v0.1.1-alpha
        environment:
            - STROOM_NODE=node1a
            - STROOM_RACK=rack
            - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
            - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
            - STROOM_JDBC_DRIVER_URL=jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://stroom-stats-db/statistics?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_POST_LOGOUT_REDIRECT_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8099/authentication/v1/logout
            # - STROOM_SECURITY_LOGIN_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/authenticationService/v1/checkCertificate
            # - STROOM_SECURITY_AUTHENTICATION_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/authenticationService/v1
            # The browser is redirected to this URL so, like the AUTH UI URL, it needs to be the advertised host.
            - STROOM_AUTH_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8099
            - STROOM_AUTH_JWT_VERIFICATIONKEY=CHANGE_ME
            - STROOM_AUTH_JWT_ISSUER=stroom
            - STROOM_AUTH_JWT_ENABLETOKENREVOCATIONCHECK=${ENABLE_TOKEN_REVOCATION_CHECK}
            - STROOM_ADVERTISED_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8080
            # This needs to be an API token issued for a user, i.e. for the admin user. 
            # Without this Stroom won't be able to make calls to it's RemoteDataSources.
            - STROOM_SECURITY_APITOKEN=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE1Mzg2NDM1NTQsInN1YiI6ImFkbWluIiwiaXNzIjoic3Ryb29tIn0.J8dqtQf9gGXQlKU_rAye46lUKlJR8-vcyrYhOD0Rxoc
            - ADMIN_CONTEXT_PATH=/stroomAdmin
            - STROOM_LOGGING_LEVEL=INFO
            - STROOM_PLUGINS_LIB_DIR=/stroom/plugins
            - STROOM_CONNECTORS_KAFKA_DEFAULT_BOOTSTRAP_SERVERS=kafka:9092
            - STROOM_CONNECTORS_KAFKA_DEFAULT_CONNECTOR_VERSION=0.10.0.1
            - STROOM_SERVICE_DISCOVERY_ZOOKEEPER_URL=zookeeper:2181
            - STROOM_DEVELOPMENT_MODE=true
        ports:
            - 8080:8080
            - 8081:8081

