version: '2.1'

services:

  stroom-annotations-ui:
    container_name: stroom-annotations-ui
    image: "${STROOM_ANNOTATIONS_UI_DOCKER_REPO:-gchq/stroom-annotations-ui}:${STROOM_ANNOTATIONS_UI_TAG:-v0.2.0-alpha.2}"
    environment:
      - ANNOTATIONS_UI_AUTHENTICATION_SERVICE_URL=https://${STROOM_AUTH_SERVICE_HOST:-stroom-auth-service}/authenticationService/v1
      - ANNOTATIONS_UI_AUTHORISATION_SERVICE_URL=https://${STROOM_AUTHORISATION_SERVICE_HOST:-stroom}/authorisationService/v1
      - ANNOTATIONS_UI_ADVERTISED_URL=https://${STROOM_ANNOTATIONS_UI_HOST:-stroom-annotations-ui}:5001
      - ANNOTATIONS_UI_APP_CLIENT_ID=stroom-annotations
      - ANNOTATIONS_UI_ANNOTATIONS_SERVICE_URL=https://${STROOM_ANNOTATIONS_SERVICE_HOST:-stroom-annotations-service}/annotationsService
    ports:
      - 5001:5000
