#Runs the latest build of stroom from dockerhub 
version: '2'

services: 

    stroom:
        container_name: stroom
        image: gchq/stroom:auth_v0.1.1-alpha
        environment:
            - STROOM_NODE=node1a
            - STROOM_RACK=rack
            - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
            - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
            - STROOM_JDBC_DRIVER_URL=jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://stroom-stats-db/statistics?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
            - STROOM_SECURITY_LOGIN_URL=http://localhost/authenticationService/v1/checkCertificate
            - STROOM_SERVICE_DISCOVERY_ZOOKEEPER_URL=zookeeper:2181
            - STROOM_AUTH_JWT_SECRET=CHANGE_ME
            - STROOM_AUTH_JWT_ISSUER=stroom
            - ADMIN_CONTEXT_PATH=/stroomAdmin
            - STROOM_LOGGING_LEVEL=DEBUG
        ports:
            - 8080:8080
            - 8081:8081

