version: '2.1'

services:

  stroom-query-elastic-ui:
    container_name: stroom-query-elastic-ui
    image: "${STROOM_ELASTIC_UI_DOCKER_REPO:-gchq/stroom-query-elastic-ui}:${STROOM_ELASTIC_UI_TAG:-v0.0.2-alpha.3}"
    environment:
      - REACT_APP_QUERY_ELASTIC_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/queryElasticService
    ports:
      - 5002:5000
