version: '2.1'

services: 

  stroom-proxy:
    container_name: stroom-proxy
    image: "${STROOM_PROXY_DOCKER_REPO:-gchq/stroom-proxy}:${STROOM_PROXY_TAG:-v5.1-LATEST}"
    ports:
      - 8090:8085
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
