version: '2.1'

services:

  stroom-query-elastic-ui:
    container_name: stroom-query-elastic-ui
    image: "gchq/stroom-query-elastic-ui:${STROOM_ELASTIC_UI_TAG:-v0.0.2-alpha.3}"
    environment:
      - QUERY_ELASTIC_UI_AUTHENTICATION_SERVICE_URL=http://stroom-auth-service:8099/authentication/v1
      - QUERY_ELASTIC_UI_AUTHORISATION_SERVICE_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}/api/authorisation/v1
      - QUERY_ELASTIC_UI_ADVERTISED_URL=http://stroom-query-elastic-ui:5002
      - QUERY_ELASTIC_UI_APP_CLIENT_ID=stroom-query-elastic
      - QUERY_ELASTIC_UI_ANNOTATIONS_SERVICE_URL=http://stroom-query-elastic-service:8299
    ports:
      - 5002:5000
