version: '2'

services:

  stroom-auth-service:
    container_name: stroom-auth-service
    image: gchq/stroom-auth-service:v0.1.1-alpha
    environment:
      - DB_USER=stroomuser
      - DB_PASSWORD=stroompassword1
      - DB_URL=jdbc:mariadb://stroom-auth-db/auth
      - JWS_SECRET=CHANGE_ME
      - ADMIN_CONTEXT_PATH=/authenticationServiceAdmin
      - AUTH_UI=http://localhost/auth/login
      - AUTHORISATION_SERVICE_URL=http://stroom:8080/api/authorisation/v1
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PATH=/canManageUsers
      - AUTHORISATION_SERVICE_CAN_MANAGE_USERS_PERMISSION=Manage Users
    ports:
      - 8099:8099
      - 8100:8100