version: '2.1'

services:

  stroom-annotations-service:
    container_name: stroom-annotations-service
    image: "${STROOM_ANNOTATIONS_SERVICE_DOCKER_REPO:-gchq/stroom-annotations-service}:${STROOM_ANNOTATIONS_SERVICE_TAG:-v0.2.0-alpha.2}"
    environment:
      - DB_USER=stroomuser
      - DB_PASSWORD=stroompassword1
      - DB_URL=jdbc:mariadb://${STROOM_ANNOTATIONS_DB_HOST:-stroom-annotations-db}:${STROOM_ANNOTATIONS_DB_PORT:-3306}/annotations
      - ADMIN_CONTEXT_PATH=/annotationsServiceAdmin
      - AUTH_UI=${STROOM_AUTH_UI_URL:-http://localhost:5000}/login
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_USER_TOKEN=43200 # 43200 minutes = 30 days
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_API_TOKEN=525600 # 525600 minutes = 1 year
      - JWS_MINUTES_UNTIL_EXPIRATION_FOR_EMAIL_RESET_TOKEN=5 # Only 5 minutes
      - AUTHORISATION_SERVICE_URL=http://${STROOM_AUTHORISATION_SERVICE_HOST:-stroom}/authorisationService/v1
      - AUTHORISATION_SERVICE_IS_AUTHORISED_PATH=/isAuthorised
    ports:
      - 8199:8199
      - 8200:8200
    entrypoint: ./wait-for-it_busybox.sh ${STROOM_ANNOTATIONS_DB_HOST:-stroom-annotations-db}:${STROOM_ANNOTATIONS_DB_PORT:-3306} -- java -jar stroom-annotations-service-all.jar server config.yml
