version: '2.1'

services: 

  stroom-stats-db:
    image:  "${MYSQL_DOCKER_REPO:-mysql}:5.6"
    container_name: stroom-stats-db
    ports:
        #expose mysql on 3307 to the host so as not to conflict with stroom-db
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${STROOM_STATS_DB_ROOT_PASSWORD:-my-secret-pw}
      - MYSQL_USER=${STROOM_STATS_DB_USERNAME:-stroomuser}
      - MYSQL_PASSWORD=${STROOM_STATS_DB_PASSWORD:-stroompassword1}
      - MYSQL_DATABASE=statistics
    volumes:
      - ${STROOM_STATS_DB_DATA_VOLUME:-~/.stroom/db_data/stroom-stats-db}:/var/lib/mysql
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
