#Runs the latest build of stroom from dockerhub 
version: '2'

services: 

    stroom:
        container_name: stroom
        image: gchq/stroom:dev-SNAPSHOT
        environment:
            - STROOM_NODE=node1a
            - STROOM_RACK=rack
            - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
            - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
            - STROOM_JDBC_DRIVER_URL=jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://stroom-stats-db/statistics?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_PLUGINS_LIB_DIR=/stroom/plugins
            - STROOM_CONNECTORS_KAFKA_DEFAULT_BOOTSTRAP_SERVERS=kafka:9092
            - STROOM_CONNECTORS_KAFKA_DEFAULT_CONNECTOR_VERSION=0.10.0.1
            - STROOM_SERVICE_DISCOVERY_ZOOKEEPER_URL=zookeeper:2181
            - STROOM_AUTH_JWT_SECRET=CHANGE_ME
            - STROOM_AUTH_JWT_ISSUER=stroom
            - STROOM_DEVELOPMENT_MODE=true
        ports:
            - 8080:8080

