version: '2.4'

services: 

  stroom-proxy-remote:
    container_name: stroom-proxy-remote
    image: "${STROOM_PROXY_DOCKER_REPO:-gchq/stroom-proxy}:${STROOM_PROXY_TAG:-v6-LATEST}"
    environment:
      #- SYNC_API_KEY=${STROOM_PROXY_REMOTE_SYNC_API_KEY:-http://stroom:8080/api/dictionary/v1}
      - CONTENT_SYNC_ENABLED=${STROOM_PROXY_REMOTE_CONTENT_SYNC_ENABLED:-true}
      - FORWARDING_ENABLED=${STROOM_PROXY_REMOTE_FORWARDING_ENABLED:-true}
        # forward to stroom-proxy-local via nginx
      - FORWARD_URL=${STROOM_PROXY_REMOTE_FORWARD_URL:-https://nginx/stroom/datafeed}
      - JAVA_OPTS=${STROOM_PROXY_REMOTE_JAVA_OPTS:- -Xms50m -Xmx1024m }
      - RECEIPT_POLICY_UUID=${STROOM_PROXY_REMOTE_RECEIPT_POLICY_UUID:-}
      - STORING_ENABLED=${STROOM_PROXY_REMOTE_STORING_ENABLED:-true}
      - STROOM_PROXY_ADMIN_PORT=8091
      - STROOM_PROXY_APP_PORT=8090
      - STROOM_PROXY_HTTPS_APP_PORT=8543
      - STROOM_PROXY_HTTPS_KEYSTORE_PASSWORD=${STROOM_PROXY_REMOTE_HTTPS_KEYSTORE_PASSWORD:-password}
      - STROOM_PROXY_HTTPS_KEYSTORE_PATH=${STROOM_PROXY_REMOTE_HTTPS_KEYSTORE_PATH:-/stroom-proxy/certs/server.jks}
      - STROOM_PROXY_HTTPS_KEYSTORE_TYPE=${STROOM_PROXY_REMOTE_HTTPS_KEYSTORE_TYPE:-JKS}
      - STROOM_PROXY_HTTPS_NEED_CLIENT_AUTH=${STROOM_PROXY_REMOTE_HTTPS_NEED_CLIENT_AUTH:-false}
      - STROOM_PROXY_HTTPS_SUPPORTED_PROTOCOLS=${STROOM_PROXY_REMOTE_HTTPS_SUPPORTED_PROTOCOLS:-TLSv1.2}
      - STROOM_PROXY_HTTPS_TRUSTSTORE_PASSWORD=${STROOM_PROXY_REMOTE_HTTPS_TRUSTSTORE_PASSWORD:-password}
      - STROOM_PROXY_HTTPS_TRUSTSTORE_PATH=${STROOM_PROXY_REMOTE_HTTPS_TRUSTSTORE_PATH:-/stroom-proxy/certs/ca.jks}
      - STROOM_PROXY_HTTPS_TRUSTSTORE_TYPE=${STROOM_PROXY_REMOTE_HTTPS_TRUSTSTORE_TYPE:-JKS}
      - STROOM_PROXY_HTTPS_WANT_CLIENT_AUTH=${STROOM_PROXY_REMOTE_HTTPS_WANT_CLIENT_AUTH:-false}
      - UPSTREAM_DICTIONARY_URL=${STROOM_PROXY_REMOTE_UPSTREAM_DICTIONARY_URL:-https://nginx/dictionaryService/v1}
      - UPSTREAM_RULE_URL=${STROOM_PROXY_REMOTE_UPSTREAM_RULE_URL:-https://nginx/rulesetService/v1}
    ports:
      - "${STROOM_PROXY_REMOTE_APP_PORT:-9090}:8090"
      - "${STROOM_PROXY_REMOTE_APP_PORT_HTTPS:-9543}:8543"
      - "${STROOM_PROXY_REMOTE_ADMIN_PORT:-9091}:8091"
    healthcheck:
      test: curl --fail --silent --head --output /dev/null http://localhost:8091/proxyAdmin/healthcheck || exit 1
      start_period: 30s 
      interval: 1m
      timeout: 5s
      retries: 3
    volumes:
      - ${STROOM_PROXY_REMOTE_VOLUME_CERTS:-../../volumes/stroom-proxy-remote/certs}:/stroom-proxy/certs:ro
      - type: volume
        source: stroom-proxy-remote_config
        target: /stroom-proxy/config
      - type: volume
        source: stroom-proxy-remote_content
        target: /stroom-proxy/content
      - type: volume
        source: stroom-proxy-remote_logs
        target: /stroom-proxy/logs
      - type: volume
        source: stroom-proxy-remote_repo
        target: /stroom-proxy/repo
    logging:
      options:
        max-size: "${STROOM_PROXY_REMOTE_STD_OUT_LOGS_MAX_SIZE:-10m}"
        max-file: "${STROOM_PROXY_REMOTE_STD_OUT_LOGS_MAX_FILES:-2}"
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"
