#Runs the latest build of stroom from dockerhub
version: '2'

services:

    stroom:
        container_name: stroom
        image: gchq/stroom:dev-SNAPSHOT
        environment:
            - STROOM_NODE=node1a
            - STROOM_RACK=rack
            - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
            - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
            - STROOM_JDBC_DRIVER_URL=jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://stroom-stats-db/statistics?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=stroompassword1
            # The browser is redirected to this URL so, like the AUTH UI URL, it needs to be the advertised host.
            - STROOM_AUTH_SERVICE_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8099
            - STROOM_AUTH_UI_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:5000
            - STROOM_AUTH_JWT_ISSUER=stroom
            - STROOM_AUTH_JWT_ENABLETOKENREVOCATIONCHECK=${ENABLE_TOKEN_REVOCATION_CHECK}
            - STROOM_ADVERTISED_URL=http://${STROOM_RESOURCES_ADVERTISED_HOST}:8080
            # This needs to be an API token issued for a user, i.e. for the admin user.
            # Without this Stroom won't be able to make calls to it's RemoteDataSources.
            - STROOM_SECURITY_API_TOKEN=eyJhbGciOiJSUzI1NiJ9.eyJleHAiOjE1NDQ4NjMwNDMsInN1YiI6InN0cm9vbVNlcnZpY2VVc2VyIiwiaXNzIjoic3Ryb29tIn0.gHJkpxeW5CjU_hBzuLhQd8Ot8XkLvhu45_-Ql4gOX96iNbl0AnKEwKu2QmMY3uVerGjYBHDczgKJlLVF_RQtFiwFLorT2P_Mv-9ShcCL0Ml-Tq-1i-_UnHMYHP5Nv-rP3ajUz-vTHwIYqi_WU-IEpIF56MCYBqeDkgQfe-I03VyfsLkWt-3f8L3AKESZirmqjPUB_SPi4vWGpyN28FuJe1KyqdCPo5QVKnrM_dpguE_aIj1Dy1sovmgO5WxFm3-hE7asW3WrnokSopNXQ1bJ3W77v4k1CnMpYDw5schQAKqUffPVGxNE6UxNunZTlRQJQqYihKkhpeiTiZMo9XCHGg
            - ADMIN_CONTEXT_PATH=/stroomAdmin
            - STROOM_LOGGING_LEVEL=INFO
            - STROOM_PLUGINS_LIB_DIR=/stroom/plugins
            - STROOM_CONNECTORS_KAFKA_DEFAULT_BOOTSTRAP_SERVERS=kafka:9092
            - STROOM_CONNECTORS_KAFKA_DEFAULT_CONNECTOR_VERSION=0.10.0.1
            - STROOM_SERVICE_DISCOVERY_ZOOKEEPER_URL=zookeeper:2181
            - STROOM_DEVELOPMENT_MODE=true
        ports:
            - 8080:8080
            - 8081:8081
