version: '2.4'

services: 

  stroom-proxy:
    container_name: stroom-proxy
    image: "${STROOM_PROXY_DOCKER_REPO:-gchq/stroom-proxy}:${STROOM_PROXY_TAG:-v6-LATEST}"
    ports:
      - "${STROOM_PROXY_APP_PORT:-8090}:${STROOM_PROXY_APP_PORT:-8090}"
      #- "${STROOM_PROXY_APP_PORT_HTTPS:-8543}:${STROOM_PROXY_APP_PORT_HTTPS:-8543}"
      - "${STROOM_PROXY_ADMIN_PORT:-8091}:${STROOM_PROXY_ADMIN_PORT:-8091}"
    volumes:
      - type: volume
        source: stroom-proxy_config
        target: /stroom-proxy/config
      - type: volume
        source: stroom-proxy_content
        target: /stroom-proxy/content
      - type: volume
        source: stroom-proxy_logs
        target: /stroom-proxy/logs
      - type: volume
        source: stroom-proxy_repo
        target: /stroom-proxy/repo
    labels:
      - "stack_name=${STACK_NAME:-<STACK_NAME>}"

        # volumes:
        #  stroom-proxy_config:
        #  stroom-proxy_content:
        #  stroom-proxy_logs:
        #  stroom-proxy_repo:
