version: '2.1'

services: 

  zookeeper:
    container_name: zookeeper
    build: 
        context: ../../../dev-resources/images/zookeeper
        args: 
           - http_proxy
           - https_proxy
           - no_proxy
    image: stroom-stats/zookeeper
    ports:
      - "2181:2181"
