#Runs the aspects of the annotations service required for integration testing
version: '2'

services:

  nginx:
      extends:
          file: ./containers/nginx.yml
          service: nginx

  stroom-annotations-db:
    extends:
          file: ./containers/stroomAnnotationsDb.yml
          service: stroom-annotations-db

  stroom-annotations-service:
      extends:
          file: ./containers/stroomAnnotationsService.yml
          service: stroom-annotations-service
      image: "gchq/stroom-annotations-service:${STROOM_ANNOTATIONS_SERVICE_TAG}"

  stroom-annotations-ui:
      extends:
          file: ./containers/stroomAnnotationsUi.yml
          service: stroom-annotations-ui
      image: "gchq/stroom-annotations-ui:${STROOM_ANNOTATIONS_UI_TAG}"

  zookeeper:
      extends:
          file: ./containers/zookeeper.yml
          service: zookeeper

  kafka:
      extends:
          file: ./containers/kafka.yml
          service: kafka
      depends_on:
        - "zookeeper"

