#Runs the whole stroom estate
version: '2'

services:

  nginx:
      extends:
          file: ./containers/nginx.yml
          service: nginx

  elasticsearch:
      extends:
          file: ./containers/elasticsearch.yml
          service: elasticsearch

  stroom-query-elastic-ui:
      extends:
          file: ./containers/stroomElasticQueryUi.yml
          service: stroom-query-elastic-ui
      depends_on:
          - stroom-query-elastic-service
      image: "gchq/stroom-query-elastic-service:${STROOM_QUERY_ELASTIC_SERVICE_TAG}"

  stroom-query-elastic-service:
      extends:
          file: ./containers/stroomElasticQueryService.yml
          service: stroom-query-elastic-service
      depends_on:
          - elasticsearch
      image: "gchq/stroom-query-elastic-ui:${STROOM_QUERY_ELASTIC_SERVICE_TAG}"

  kibana:
      extends:
          file: ./containers/kibana.yml
          service: kibana
      depends_on:
          - elasticsearch
