#For use when running Stroom in an IDE (or running Stroom's integration tests) with all services/resources it needs e.g. service discovery, kafka, etc. but no HBase
version: '2'

services:

  nginx:
      extends:
          file: ./containers/nginx.yml
          service: nginx

  kafka:
      extends:
          file: ./containers/kafka.yml
          service: kafka
      depends_on:
        - "zookeeper"

  stroom-db:
      extends:
          file: ./containers/stroomDb.yml
          service: stroom-db

  stroom-stats-db:
      extends:
          file: ./containers/stroomStatsDb.yml
          service: stroom-stats-db

  stroom-annotations-service:
      extends:
          file: ./containers/stroomAnnotationsService.yml
          service: stroom-annotations-service
      image: "gchq/stroom-annotations-service:${STROOM_ANNOTATIONS_TAG}"

  stroom-annotations-ui:
      extends:
          file: ./containers/stroomAnnotationsUi.yml
          service: stroom-annotations-ui
      image: "gchq/stroom-annotations-ui:${STROOM_ANNOTATIONS_TAG}"

  stroom-annotations-db:
    extends:
          file: ./containers/stroomAnnotationsDb.yml
          service: stroom-annotations-db

  zookeeper:
      extends:
          file: ./containers/zookeeper.yml
          service: zookeeper

