#Runs stroom build 5.0-beta.21 from dockerhub along with its databases and zookeeper
version: '2'

services: 

  mysql-stroom:
      extends:
          file: stroom-dbs.yml
          service: mysql-stroom

  mysql-stats:
      extends:
          file: stroom-dbs.yml
          service: mysql-stats

  zookeeper:
      extends:
          file: zookeeper.yml
          service: zookeeper

  stroom:
      extends:
          file: stroom.yml
          service: stroom
      image: gchq/stroom:5.0-beta.31
      depends_on:
        - "mysql-stroom"
        - "mysql-stats"
        - "zookeeper"

#TODO add stroom-stats, kafka and hbase
