#Runs the whole stroom estate
version: '2'

services: 

  stroom-db:
      extends:
          file: ./containers/stroomDb.yml
          service: stroom-db

  stroom-auth-db:
      extends:
          file: ./containers/stroomAuthDb.yml
          service: stroom-auth-db

  stroom:
      extends:
          file: ./containers/stroom.yml
          service: stroom
      image: "gchq/stroom:${STROOM_TAG}"
      depends_on:
        - "stroom-db"
