#Runs the two MySQL datbases required by stroom (and for the moment stroom-stats)
version: '2'

services: 

  mysql-stroom:
    image: mysql:5.6
    container_name: stroom-db
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=stroomuser
      - MYSQL_PASSWORD=stroompassword1
      - MYSQL_DATABASE=stroom

  mysql-stats:
    image: mysql:5.6
    container_name: stroom-stats-db
    ports:
        #expose mysql on 3307 to the host so as not to conflict with stroom-db
      - "3308:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=stroomuser
      - MYSQL_PASSWORD=stroompassword1
      - MYSQL_DATABASE=statistics

  stroom-auth-service-db:
    image: mariadb:10.3.0
    container_name: stroom-auth-service-db
    ports:
        # Expose mysql on 3309 to the host so as not to conflict with stroom-db or stroom-stats-db
      - "3309:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=my-secret-pw
      - MYSQL_USER=stroomuser
      - MYSQL_PASSWORD=stroompassword1
      - MYSQL_DATABASE=auth
