#Runs the latest build of stroom from dockerhub 
version: '2'

services: 

    stroom:
        container_name: stroom
        image: gchq/stroom:v6.0.0-SNAPSHOT
        environment:
            - STROOM_NODE=node1a
            - STROOM_RACK=rack
            - STROOM_JPA_DIALECT=org.hibernate.dialect.MySQLInnoDBDialect
            - STROOM_JDBC_DRIVER_CLASS_NAME=com.mysql.jdbc.Driver
            - STROOM_JDBC_DRIVER_URL=jdbc:mysql://stroom-db/stroom?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_JDBC_DRIVER_PASSWORD=stroompassword1
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_URL=jdbc:mysql://stroom-stats-db/statistics?useUnicode=yes&characterEncoding=UTF-8
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_USERNAME=stroomuser
            - STROOM_STATISTICS_SQL_JDBC_DRIVER_PASSWORD=stroompassword1
        ports:
            - 8080:8080

