#Runs the whole stroom estate
version: '2'

services: 

  stroom-db:
      extends:
          file: ./containers/stroomDb.yml
          service: stroom-db

  stroom-stats-db:
      extends:
          file: ./containers/stroomStatsDb.yml
          service: stroom-stats-db

  stroom:
      extends:
          file: ./containers/stroom.yml
          service: stroom
      image: "gchq/stroom:${STROOM_TAG}"
      depends_on:
        - "stroom-db"
        - "stroom-stats-db"
