- name: Download stack
  get_url:
    url: "{{ stroom_url }}"
    dest: "{{ generated_path }}"
    checksum: "sha256:{{ stroom_url }}.sha256"
  register: download_info

  # FIXME: I can't get the unarchive module to work on macOS or Ubuntu. Ansible complains about /bin/tar not being able
  # to handle the archive. It untars manually without problems, so I'l just do that.
- name: Unpack Stroom's distribution tar
  command: "tar -xvf {{playbook_dir}}/{{download_info.dest}} --directory {{ generated_path }}"

- name: Delete the archive
  file:
    path: "{{ download_info.dest }}"
    state: absent
