- name: Performing '{{op}}' on '{{stack_type}}'
  command: chdir={{home}}/{{stack_type}}/{{stack_type}}-{{stack_version}}/ ./{{op}}.sh -y
  # Sometimes get a tput error if we don't do this.
  environment:
    TERM: vt100
  register: stack_op
  # This check is a bit more complicated because 'stdout' doesn't always exist on 'stack_op'
  failed_when: "'stdout' in stack_op and 'UNHEALTHY' in stack_op.stdout"

- debug:
    msg: "{{stack_op.stdout}}"
  when: "'stdout' in stack_op and (op=='info' or op=='status' or op=='health' or op=='logs' or op=='show_config')"
    
- debug:
    msg: "{{stack_op.stderr}}"
  when: "'stderr' in stack_op"
