- name: Make sure the '{{home}}/Downloads' folder exists 
  file:
    path: "{{home}}/Downloads"
    state: directory

- name: Get the {{stack_type}} stack
  get_url:
    url: https://github.com/gchq/stroom-resources/releases/download/stroom-stacks-{{stack_version}}/{{stack_type}}-{{stack_version}}.tar.gz
    dest:  "{{home}}/Downloads/"

# The archive extracts to ./stroom_dbs so we'll put it straight into ~
- name: Un-tar the downloaded {{stack_type}} stack
  unarchive:
    src: "{{home}}/Downloads/{{stack_type}}-{{stack_version}}.tar.gz"
    dest: "{{home}}/"
    remote_src: yes
