server:
  applicationContextPath: ${APPLICATION_CONTEXT_PATH:- /}
  adminContextPath: ${ADMIN_CONTEXT_PATH:- /stroomAdmin}
  applicationConnectors:
    - type: http
      port: ${STROOM_APP_PORT:-8080}
  adminConnectors:
    - type: http
      port: ${STROOM_ADMIN_PORT:-8081}

  requestLog:
    appenders:
    - type: file
      currentLogFilename: /stroom/logs/access/access.log
      threshold: ALL
      queueSize: 256
      discardingThreshold: 0
      archive: true
      archivedLogFilenamePattern: /stroom/logs/access/access-%d{yyyy-MM-dd'T'HH:mm}.log.gz
      archivedFileCount: 100
      timeZone: UTC

logging:
  level: ${STROOM_LOGGING_LEVEL:- WARN}
  loggers:
    stroom: INFO
    io.dropwizard: INFO
    org.eclipse.jetty: INFO
    org.flywaydb: INFO
    org.hibernate: ERROR
    "event-logger":
      level: INFO
      additive: false
      appenders:
      - type: file
        currentLogFilename: /stroom/logs/user/user.log
        threshold: ALL
        queueSize: 256
        discardingThreshold: 0
        archive: true
        archivedLogFilenamePattern: /stroom/logs/user/user-%d{yyyy-MM-dd'T'HH:mm}.log.gz
        archivedFileCount: 100
        timeZone: UTC
        logFormat: "%msg%n"

  appenders:
    # stdout for docker
    # Comment out for non-dockered environments
  - type: console
    logFormat: "%highlight(%-6level) [%d{\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\",UTC}] [%green(%t)] %cyan(%logger) - %X{code} %msg %n"
    timeZone: UTC
    # Minute rolled files for stroom/datafeed, will be curl'd/deleted by stroom-log-sender
  - type: file
    currentLogFilename: /stroom/logs/app/app.log
    threshold: ALL
    queueSize: 256
    discardingThreshold: 0
    archive: true
    archivedLogFilenamePattern: /stroom/logs/app/app-%d{yyyy-MM-dd'T'HH:mm}.log.gz
    # One week using minute files
    archivedFileCount: 10080
    timeZone: UTC
    logFormat: "%-6level [%d{\"yyyy-MM-dd'T'HH:mm:ss.SSS'Z'\",UTC}] [%t] %logger - %X{code} %msg %n"
    # Size rolled logs for admins (10x100M), not curl'd to stroom
    # Un-comment for non-dockered environments
    #  - type: file
    #    currentLogFilename: /stroom/logs/app.log
    #    threshold: ALL
    #    queueSize: 256
    #    discardingThreshold: 0
    #    archive: true
    #    archivedLogFilenamePattern: /stroom/logs/app-%i.log
    #    archivedFileCount: 10
    #    maxFileSize: "100MB"
    #    timeZone: UTC
    #    logFormat: "%-6level [%d{\"yyyy-MM-dd\",UTC}] [%t] %logger - %X{code} %msg %n"


externalConfig: "stroom.conf"

