- name: Clone GCHQ git repositories
  hosts: localhost
  tasks:
    - name: Clone stroom
      git:
        repo: git@github.com:gchq/{{item}}.git
        dest: ~/github/gchq/{{item}}
        accept_hostkey: yes
      loop:
        - event-logging
        - event-logging-schema
        - stroom
        - stroom-auth
        - stroom-clients
        - stroom-content
        - stroom-docs
        - stroom-expression
        - stroom-query
        - stroom-resources
        - stroom-stats
        - stroom-ui
